name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Apk And Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          repository: cy745/lmusic
          ssh-strict: true
          persist-credentials: true
          clean: true
          fetch-depth: 1
          lfs: false
          submodules: recursive

      - name: Create the Keystore from Secrets to Sign the App
        env:
          KEYSTORE_JKS_BASE64: ${{ secrets.KEYSTORE_JKS_BASE64 }}
          KEYSTORE_PROPERTIES_BASE64: ${{ secrets.KEYSTORE_PROPERTIES_BASE64 }}
        run: |
          # Import keystore from secrets
          ls -all
          echo $KEYSTORE_JKS_BASE64 | base64 -di > ${{ github.workspace }}/keystore.jks
          echo $KEYSTORE_PROPERTIES_BASE64 | base64 -di > ${{ github.workspace }}/keystore.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Apk to Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: LMusic-Apks
          path: ${{ github.workspace }}/app/build/outputs/apk/release/*.apk
